version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

  api:
    build: .
    restart: always
    ports:
      - 5000:80
    depends_on:
      - db